import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core'
import { RouterLink } from '@angular/router'
import { TranslocoPipe } from '@jsverse/transloco'
import { injectActiveLang } from '../../i18n/active-lang'
import { PlanHighlight } from '../plan-highlight'
import { PLAN_FRAGMENTS, PlanPage, planPageCommands } from '../plan-links'

/**
 * The isometric plan of one FerrisGit instance: its crates, stores and job executors. The template is generated by
 * scripts/build-plan.mjs (`npm run plan`), so edit the script, not architecture-plan.html. The labels are Transloco
 * bindings, hence real text in the prerendered page. The plan draws itself when it scrolls into view
 * (architecture-plan.scss) and is complete from the start without scripts or with reduced motion. Its seven circles
 * lead to the tiles or sections of the page that carries it and light them up on hover (PlanHighlight); the
 * keyboard uses the list under the plan (PlanFigure).
 */
@Component({
  selector: 'app-architecture-plan',
  imports: [RouterLink, TranslocoPipe],
  templateUrl: './architecture-plan.html',
  styleUrl: './architecture-plan.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ArchitecturePlan {
  private readonly lang = injectActiveLang()
  private readonly highlight = inject(PlanHighlight)

  /** The page the plan sits on, which decides where the circles lead. */
  readonly page = input<PlanPage>('home')

  protected readonly highlighted = this.highlight.active
  protected readonly pageLink = computed(() => planPageCommands(this.page(), this.lang()))

  protected fragment(n: number): string {
    return PLAN_FRAGMENTS[this.page()][n - 1]
  }

  protected point(number: number | null): void {
    this.highlight.set(number)
  }
}
