// Writes the nginx include that sets the Content-Security-Policy header, from the pages the build produced.
//
// An inline script, if a page ever had one, would be allowed by the hash of its content rather than 'unsafe-inline',
// so the hashes have to follow the build: this runs in the Docker build, after `npm run build`. No page has one today
// (scripts/check-dist.mjs enforces it), which leaves script-src at 'self'.
//
// Usage: node docker/generate-csp.mjs <browser output directory> <file to write>
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const [root, output] = process.argv.slice(2)
if (!root || !output) {
  console.error('usage: generate-csp.mjs <browser output directory> <file to write>')
  process.exit(2)
}

function htmlFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? htmlFiles(join(dir, entry.name))
      : entry.name.endsWith('.html')
        ? [join(dir, entry.name)]
        : [],
  )
}

const scriptPattern = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi
// JSON data blocks (Angular's transfer state, structured data) are never executed, so the policy does not apply.
const dataType = /\btype\s*=\s*["']?(?:application\/(?:ld\+)?json|importmap|speculationrules)/i
// A hash cannot allow an inline handler without 'unsafe-hashes'. Failing is better than weakening the policy silently.
const inlineHandler = /<[a-z][^>]*\son[a-z]+\s*=/i

const hashes = new Set()
const problems = []
for (const file of htmlFiles(root)) {
  const html = readFileSync(file, 'utf8')
  if (inlineHandler.test(html)) {
    problems.push(`${file}: inline event handler attribute`)
  }
  for (const [, attributes, body] of html.matchAll(scriptPattern)) {
    if (/\bsrc\s*=/i.test(attributes) || dataType.test(attributes) || body.trim() === '') {
      continue
    }
    hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`)
  }
}
if (problems.length > 0) {
  console.error(problems.join('\n'))
  process.exit(1)
}

const scriptSrc = ["'self'", ...[...hashes].sort()].join(' ')
const policy = [
  "default-src 'self'",
  `script-src ${scriptSrc}`,
  // Angular adds component styles as <style> elements at runtime, which only 'unsafe-inline' allows without a nonce.
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
].join('; ')

writeFileSync(
  output,
  `# Generated by docker/generate-csp.mjs at image build time: ${hashes.size} inline script hash(es).\nadd_header Content-Security-Policy "${policy}" always;\n`,
)
console.log(`CSP written to ${output} with ${hashes.size} inline script hash(es).`)
