// French wording for the Gabarit auth kit. `provideFerrisgitAuth()` provides it app-wide so the nested pieces
// (enrolment, QR, backup codes) are French too.
import type { AuthLabels } from '@masmarino/gabarit';

const TOO_MANY_ATTEMPTS = 'Trop de tentatives, réessayez dans quelques minutes';
const PASSKEYS_UNAVAILABLE = "Les clés d'accès ne sont pas disponibles sur ce serveur.";
const BROWSER_UNSUPPORTED = "Ce navigateur ne prend pas en charge les clés d'accès.";
const LOGIN_EXPIRED = 'Votre connexion a expiré, reconnectez-vous.';
const ALREADY_REGISTERED = 'Cette clé est déjà enregistrée';
const CANCELLED = 'Opération annulée';
const DEFAULT_PASSKEY_NAME = "Clé d'accès";
const NAME_TOO_LONG = (max: number) => `Le nom ne doit pas dépasser ${max} caractères`;
const NAME_CONTROL = 'Le nom ne peut pas contenir de caractères de contrôle';
const SCAN_LEAD = "Scannez ce QR code avec votre application d'authentification, puis saisissez le code à 6 chiffres qu'elle affiche.";
const LAST_FACTOR = "C'est votre dernier facteur : vous devrez en configurer un nouveau à la prochaine connexion.";
const SIGNED_OUT = 'Vous avez été déconnecté. Reconnectez-vous pour continuer.';
const on = (absolute: boolean) => (absolute ? ' le' : '');

export const FR_AUTH_LABELS = {
  totpQr: {
    fallback: "Le QR code n'a pas pu être affiché : saisissez la clé ci-dessous dans votre application.",
    imageAlt: "QR code à scanner avec votre application d'authentification",
    secretLabel: 'Ou saisissez cette clé dans votre application',
    fallbackSecretLabel: 'Clé de configuration',
    copyLabel: 'Copier la clé de configuration',
    copied: 'Copié',
    copyFailed: 'Copie impossible, clé sélectionnée',
  },
  backupCodes: {
    listLabel: 'Codes de secours',
    copy: 'Copier les codes',
    copied: 'Codes copiés',
    copyFailed: 'Copie impossible, codes sélectionnés',
    download: 'Télécharger',
    acknowledge: "J'ai enregistré mes codes de secours",
    fileName: 'ferrisgit-codes-de-secours.txt',
    fileTitle: 'FerrisGit - codes de secours',
    fileNotice: "Chaque code ne peut être utilisé qu'une seule fois. Conservez-les dans un endroit sûr.",
  },
  mfaEnrollment: {
    step: (current, total) => `Étape ${current} sur ${total}`,
    choiceHeading: 'Protégez votre compte',
    scanHeading: 'Configurez votre application',
    passkeyHeading: "Créez votre clé d'accès",
    codesHeading: 'Conservez vos codes de secours',
    mandatory: 'La double authentification est obligatoire pour sécuriser votre compte.',
    choiceLead: 'Choisissez comment vous confirmerez votre identité à chaque connexion.',
    passkeyOption: "Clé d'accès",
    recommended: 'Recommandé',
    passkeyOptionText: 'Touch ID, Windows Hello, un code PIN ou une clé de sécurité : rien à saisir, et impossible à hameçonner.',
    usePasskey: "Utiliser une clé d'accès",
    appOption: "Application d'authentification",
    appOptionText: 'Google Authenticator, Authy, 1Password… : un code à 6 chiffres à saisir à chaque connexion.',
    useApp: 'Utiliser une application',
    preparing: 'Préparation en cours',
    back: 'Retour',
    todoInstall: "Installez une application d'authentification (Google Authenticator, Authy, 1Password…).",
    todoScan: "Scannez le QR code affiché à l'étape suivante et saisissez le code à 6 chiffres.",
    todoKeep: 'Conservez vos codes de secours : ils vous serviront si vous perdez votre téléphone.',
    begin: 'Commencer',
    scanLead: SCAN_LEAD,
    codeLabel: 'Code à 6 chiffres',
    activate: 'Activer',
    verifying: 'Vérification en cours',
    passkeyLead: 'Donnez un nom à cette clé pour la reconnaître plus tard, puis validez avec votre appareil : Touch ID, Windows Hello, code PIN ou clé de sécurité.',
    passkeyNameLabel: 'Nom de la clé (facultatif)',
    defaultPasskeyName: DEFAULT_PASSKEY_NAME,
    createPasskey: "Créer la clé d'accès",
    creating: 'Création en cours',
    promptOpen: 'Validez sur votre appareil pour créer la clé.',
    codesLead: (factor) =>
      `La double authentification est activée. Ces codes ne s'afficheront plus : ils vous permettent de vous connecter si vous perdez l'accès à ${factor === 'passkey' ? "votre clé d'accès" : 'votre application'}, et chacun ne fonctionne qu'une seule fois.`,
    continue: 'Continuer',
    enterCode: 'Saisissez le code à 6 chiffres de votre application',
    wrongCode: 'Code incorrect',
    startFailed: "La configuration n'a pas pu démarrer, réessayez.",
    activationFailed: "L'activation a échoué, réessayez.",
    passkeyFailed: "La clé d'accès n'a pas pu être créée, réessayez.",
    alreadyRegistered: ALREADY_REGISTERED,
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    alreadySetUp: 'La double authentification est déjà configurée, reconnectez-vous.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
    nameTooLong: NAME_TOO_LONG,
    nameControlCharacters: NAME_CONTROL,
  },
  login: {
    heading: 'Connexion',
    intro: 'Connectez-vous pour retrouver vos dépôts, tickets et demandes de fusion.',
    challengeHeading: 'Vérification en deux étapes',
    enrollmentHeading: 'Double authentification',
    username: "Nom d'utilisateur",
    password: 'Mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Se connecter',
    submitting: 'Connexion en cours',
    registerPrompt: 'Pas encore de compte ?',
    wrongCredentials: "Nom d'utilisateur ou mot de passe incorrect",
    loginFailed: 'La connexion a échoué, réessayez.',
    introBackupCode: "Saisissez l'un de vos codes de secours. Chaque code ne fonctionne qu'une seule fois.",
    introPasskeyOrCode: "Utilisez votre clé d'accès, ou saisissez le code à 6 chiffres de votre application.",
    introPasskey: "Confirmez qu'il s'agit bien de vous avec votre clé d'accès : empreinte, visage, code de l'appareil ou clé de sécurité.",
    introCode: "Saisissez le code à 6 chiffres affiché par votre application d'authentification.",
    blockedByServer: `${PASSKEYS_UNAVAILABLE} Utilisez un code de secours.`,
    blockedByBrowser: "Ce navigateur ne prend pas en charge les clés d'accès. Utilisez un code de secours.",
    backToPasskeyOrApp: "Utiliser ma clé d'accès ou mon application",
    backToPasskey: "Utiliser ma clé d'accès",
    backToApp: 'Utiliser le code de mon application',
    useBackupCode: 'Utiliser un code de secours',
    back: 'Retour',
    backupCodeLabel: 'Code de secours',
    codeLabel: 'Code à 6 chiffres',
    verify: 'Vérifier',
    verifying: 'Vérification en cours',
    usePasskey: "Utiliser une clé d'accès",
    passkeyValidating: 'Validation en cours',
    or: 'ou',
    passkeyPrompt: 'Validez sur votre appareil pour vous connecter.',
    enterBackupCode: 'Saisissez un code de secours',
    enterCode: 'Saisissez le code à 6 chiffres de votre application',
    wrongCode: 'Code incorrect',
    verifyFailed: 'La vérification a échoué, réessayez.',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeyRefused: "Clé d'accès refusée",
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  register: {
    heading: 'Créer un compte',
    intro: 'Rejoignez FerrisGit pour héberger vos dépôts, tickets et demandes de fusion.',
    enrollmentHeading: 'Double authentification',
    loading: 'Chargement en cours',
    closedHeading: 'Les inscriptions sont fermées',
    closedMessage: "Cette instance n'accepte pas les inscriptions libres. Demandez une invitation à un administrateur : vous recevrez un lien par e-mail pour activer votre compte.",
    signIn: 'Se connecter',
    createdHeading: 'Votre compte est créé',
    createdMessage: 'Connectez-vous avec votre mot de passe pour terminer la configuration de la double authentification, obligatoire avant de commencer.',
    enrollmentExpired: 'La configuration a expiré. ',
    createdName: "Votre nom d'utilisateur :",
    username: "Nom d'utilisateur",
    usernameHint: '3 à 32 caractères, lettres, chiffres, - et _. Enregistré en minuscules.',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    passwordHint: (min) => `Au moins ${min} caractères.`,
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Créer mon compte',
    submitting: 'Création du compte en cours',
    signInPrompt: 'Vous avez déjà un compte ?',
    usernameEmpty: "Saisissez un nom d'utilisateur",
    usernameInvalid: 'Commencez par une lettre ; 3 à 32 caractères : lettres, chiffres, - et _',
    emailEmpty: 'Saisissez votre adresse e-mail',
    emailInvalid: 'Saisissez une adresse e-mail valide, par exemple nom@exemple.fr',
    passwordEmpty: 'Saisissez un mot de passe',
    passwordTooShort: (min) => `Au moins ${min} caractères`,
    invalid: 'Vérifiez les champs',
    reserved: "Ce nom d'utilisateur n'est pas disponible",
    taken: "Ce nom d'utilisateur ou cette adresse e-mail est déjà utilisé",
    failed: 'La création du compte a échoué, réessayez.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  activate: {
    heading: 'Activez votre compte',
    intro: 'Choisissez le mot de passe de votre compte. La double authentification sera configurée à votre première connexion.',
    password: 'Nouveau mot de passe',
    passwordHint: (min) => `Au moins ${min} caractères.`,
    confirmation: 'Confirmez le mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Activer mon compte',
    submitting: 'Activation en cours',
    signInPrompt: 'Votre compte est déjà actif ?',
    successHeading: 'Votre compte est activé',
    successMessage: 'Vous pouvez maintenant vous connecter. Nous vous guiderons ensuite pour protéger votre compte avec la double authentification.',
    invalidHeading: 'Ce lien ne fonctionne pas',
    invalidMessage: "Ce lien est invalide ou a expiré. Si vous vous êtes inscrit vous-même, inscrivez-vous de nouveau avec les mêmes informations pour en recevoir un nouveau. Sinon, demandez à un administrateur de vous renvoyer une invitation.",
    signIn: 'Se connecter',
    passwordEmpty: 'Saisissez un mot de passe',
    passwordTooShort: (min) => `Au moins ${min} caractères`,
    confirmationEmpty: 'Confirmez votre mot de passe',
    mismatch: 'Les mots de passe ne correspondent pas',
    weakPassword: (min) => `Le mot de passe doit comporter au moins ${min} caractères`,
    failed: "L'activation a échoué, réessayez.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  // The kit's intro doesn't mention the old password, but our server voids it on an admin reset, so ours says so.
  resetPassword: {
    heading: 'Choisissez un nouveau mot de passe',
    intro: 'Un administrateur a réinitialisé le mot de passe de votre compte : votre ancien mot de passe ne fonctionne plus. Choisissez-en un nouveau pour vous reconnecter.',
    password: 'Nouveau mot de passe',
    passwordHint: (min) => `Au moins ${min} caractères.`,
    confirmation: 'Confirmez le nouveau mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Enregistrer le mot de passe',
    submitting: 'Enregistrement en cours',
    signInPrompt: 'Votre nouveau mot de passe est déjà choisi ?',
    successHeading: 'Votre mot de passe a été modifié',
    successMessage: 'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    invalidHeading: 'Ce lien ne fonctionne pas',
    invalidMessage: 'Ce lien de réinitialisation est invalide ou a expiré. Demandez à un administrateur de vous en envoyer un nouveau.',
    signIn: 'Se connecter',
    passwordEmpty: 'Saisissez un nouveau mot de passe',
    passwordTooShort: (min) => `Au moins ${min} caractères`,
    confirmationEmpty: 'Confirmez votre nouveau mot de passe',
    mismatch: 'Les mots de passe ne correspondent pas',
    weakPassword: (min) => `Le mot de passe doit comporter au moins ${min} caractères`,
    failed: "Le nouveau mot de passe n'a pas pu être enregistré, réessayez.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  mfaSettings: {
    heading: "Application d'authentification",
    enrollingHeading: "Configurer l'application d'authentification",
    codesHeading: 'Codes de secours',
    help: 'Google Authenticator, Authy, 1Password… : toute application TOTP convient.',
    codesHelp: "Conservez-les : ils ne s'affichent qu'une seule fois.",
    loading: 'Chargement de la double authentification…',
    loadFailed: "La double authentification n'a pas pu être chargée.",
    retry: 'Réessayer',
    enrollLead: 'Confirmez votre mot de passe pour commencer la configuration.',
    enrollSubmit: 'Continuer',
    enrollBusy: 'Préparation en cours',
    enrollFailed: "La configuration n'a pas pu démarrer, réessayez.",
    regenerateLead: 'Confirmez votre mot de passe pour générer 10 nouveaux codes. Les anciens cesseront de fonctionner dès maintenant.',
    regenerateSubmit: 'Régénérer',
    regenerateBusy: 'Régénération en cours',
    regenerateFailed: "Les codes de secours n'ont pas pu être régénérés, réessayez.",
    disableSubmit: 'Continuer',
    disableCheckBusy: 'Vérification en cours',
    disableFailed: "La double authentification n'a pas pu être réinitialisée, réessayez.",
    removeTitle: "Supprimer l'application d'authentification",
    removeHelp: "Supprime votre application actuelle. Vous serez déconnecté de tous vos appareils et vous vous reconnecterez avec votre clé d'accès.",
    removeAction: 'Supprimer',
    removeDialogHeading: "Supprimer l'application d'authentification ?",
    removeDialogMessage: "Vous serez déconnecté de tous vos appareils. Vous vous reconnecterez avec votre clé d'accès, sans application.",
    removePromptLead: "Confirmez votre mot de passe pour supprimer votre application d'authentification.",
    removeBusy: 'Suppression en cours',
    resetTitle: 'Réinitialiser la double authentification',
    resetHelp: 'Retire votre application actuelle. Vous serez déconnecté de tous vos appareils et devrez en configurer une nouvelle à votre prochaine connexion.',
    resetAction: 'Réinitialiser',
    resetDialogHeading: 'Réinitialiser la double authentification ?',
    resetDialogMessage: "Vous serez déconnecté et devrez configurer une nouvelle application d'authentification à votre prochaine connexion.",
    resetPromptLead: 'Confirmez votre mot de passe pour réinitialiser la double authentification.',
    resetBusy: 'Réinitialisation en cours',
    codesLeft: (count) => (count === 0 ? 'Aucun code de secours restant' : count === 1 ? '1 code de secours restant' : `${count} codes de secours restants`),
    lowCodes: "Régénérez-en pour ne pas perdre l'accès à votre compte.",
    scanLead: SCAN_LEAD,
    codeLabel: 'Code à 6 chiffres',
    activate: 'Activer',
    verifying: 'Vérification en cours',
    cancel: 'Annuler',
    close: 'Fermer',
    codesLeadEnrolled: "La double authentification est activée. Ces codes ne s'afficheront plus : ils vous permettent de vous connecter si vous perdez l'accès à votre application, et chacun ne fonctionne qu'une seule fois.",
    codesLeadRegenerated: "Voici vos nouveaux codes de secours. Les anciens codes ne fonctionnent plus. Ces codes ne s'afficheront plus, et chacun ne fonctionne qu'une seule fois.",
    dontLeave: 'Ne quittez pas cette page avant de les avoir enregistrés.',
    done: 'Terminé',
    appConfigured: 'Application configurée',
    enabled: 'Activée',
    appHelpWithPasskey: "Un code à 6 chiffres, généré par votre application, peut remplacer votre clé d'accès après votre mot de passe.",
    appHelp: 'Un code à 6 chiffres, généré par votre application, est demandé après votre mot de passe.',
    noApp: 'Aucune application configurée',
    optional: 'Facultative',
    noAppHelp: "Votre clé d'accès suffit pour vous connecter. Ajoutez une application pour disposer d'un second moyen : elle génère un code à 6 chiffres.",
    addApp: 'Ajouter une application',
    backupCodesTitle: 'Codes de secours',
    backupCodesHelp: "Chaque code ne fonctionne qu'une fois. En générer de nouveaux invalide les précédents.",
    regenerateCodes: 'Régénérer les codes de secours',
    noFactorWarning: 'La double authentification est obligatoire : vous devrez la configurer à votre prochaine connexion.',
    setUpNow: 'Configurer maintenant',
    currentPassword: 'Mot de passe actuel',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    enterPassword: 'Saisissez votre mot de passe',
    wrongPassword: 'Mot de passe incorrect',
    enterCode: 'Saisissez le code à 6 chiffres de votre application',
    wrongCode: 'Code incorrect',
    activationFailed: "L'activation a échoué, réessayez.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
    signedOut: SIGNED_OUT,
  },
  passkeySettings: {
    heading: "Clés d'accès",
    description: "Validez votre connexion avec l'empreinte digitale, le visage ou le code de votre appareil, ou avec une clé de sécurité.",
    loading: "Chargement des clés d'accès…",
    loadFailed: "Les clés d'accès n'ont pas pu être chargées.",
    retry: 'Réessayer',
    browserBlocked: "Ce navigateur ne prend pas en charge les clés d'accès : vous ne pouvez pas en ajouter ici, mais vous pouvez supprimer celles que vous avez déjà.",
    serverBlocked: `${PASSKEYS_UNAVAILABLE} Vous ne pouvez pas en ajouter, mais vous pouvez supprimer celles que vous avez déjà.`,
    emptyHeading: "Aucune clé d'accès",
    emptyMessage: "Ajoutez-en une pour valider votre connexion d'un geste, sans code à recopier.",
    listLabel: "Clés d'accès enregistrées",
    added: (absolute) => `Ajoutée${on(absolute)}`,
    lastUsed: (absolute) => `Dernière utilisation${on(absolute)}`,
    neverUsed: 'Jamais utilisée',
    delete: 'Supprimer',
    deleteKey: (name) => `Supprimer la clé ${name}`,
    passkeyAdded: (name) => `Clé d'accès « ${name} » ajoutée.`,
    passkeyGone: (name) => `La clé d'accès « ${name} » n'existe plus.`,
    addPasskey: "Ajouter une clé d'accès",
    finishAppFirst: "Terminez d'abord la configuration de l'application d'authentification.",
    deleteDialogHeading: "Supprimer cette clé d'accès ?",
    deleteDialogMessage: (name, lastFactor) =>
      `« ${name} » ne permettra plus de vous connecter. Vous serez déconnecté de tous vos appareils et devrez vous reconnecter.` + (lastFactor ? ` ${LAST_FACTOR}` : ''),
    deleteConfirm: 'Supprimer',
    cancel: 'Annuler',
    close: 'Fermer',
    deleting: 'Suppression en cours',
    addLead: 'Nommez cette clé et confirmez votre mot de passe : votre appareil vous demandera ensuite de valider.',
    promptOpen: 'Validez sur votre appareil pour créer la clé.',
    nameLabel: 'Nom de la clé (facultatif)',
    defaultPasskeyName: DEFAULT_PASSKEY_NAME,
    currentPassword: 'Mot de passe actuel',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    create: "Créer la clé d'accès",
    creating: 'Création en cours',
    deleteLead: (name) => `Confirmez votre mot de passe pour supprimer « ${name} ».`,
    lastFactorWarning: LAST_FACTOR,
    continue: 'Continuer',
    checking: 'Vérification en cours',
    nameTooLong: NAME_TOO_LONG,
    nameControlCharacters: NAME_CONTROL,
    enterPassword: 'Saisissez votre mot de passe',
    wrongPassword: 'Mot de passe incorrect',
    tooManyPasskeys: "Vous avez atteint le nombre maximal de clés d'accès : supprimez-en une avant d'en ajouter.",
    alreadyRegistered: ALREADY_REGISTERED,
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    addFailed: "La clé d'accès n'a pas pu être créée, réessayez.",
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    deleteFailed: "La clé d'accès n'a pas pu être supprimée, réessayez.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
    signedOut: SIGNED_OUT,
  },
} satisfies { [K in keyof AuthLabels]-?: Required<NonNullable<AuthLabels[K]>> };
