apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ferrisgit-website.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ferrisgit-website.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
